#!/bin/bash
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op1056_projset4_instance2.lp > ../output_details/af_st_expanded_op1056_projset4_instance2.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op10720_projset10_instance2.lp > ../output_details/af_st_expanded_op10720_projset10_instance2.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op12_projset2.lp > ../output_details/af_st_expanded_op12_projset2.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op13336_projset10_instance3.lp > ../output_details/af_st_expanded_op13336_projset10_instance3.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op1600_projset10_instance3.lp > ../output_details/af_st_expanded_op1600_projset10_instance3.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op1640_projset6_instance1.lp > ../output_details/af_st_expanded_op1640_projset6_instance1.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op17144_projset10_instance3.lp > ../output_details/af_st_expanded_op17144_projset10_instance3.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op1780_projset5_instance2.lp > ../output_details/af_st_expanded_op1780_projset5_instance2.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op1920_projset11_instance1.lp > ../output_details/af_st_expanded_op1920_projset11_instance1.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op23392_projset10_instance3.lp > ../output_details/af_st_expanded_op23392_projset10_instance3.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op264_projset3_instance1.lp > ../output_details/af_st_expanded_op264_projset3_instance1.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op2828_projset8_instance1.lp > ../output_details/af_st_expanded_op2828_projset8_instance1.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op2_projset12.lp > ../output_details/af_st_expanded_op2_projset12.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op3344_projset5_instancefull.lp > ../output_details/af_st_expanded_op3344_projset5_instancefull.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op3456_projset10_instance3.lp > ../output_details/af_st_expanded_op3456_projset10_instance3.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op380_projset5_instance1.lp > ../output_details/af_st_expanded_op380_projset5_instance1.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op392_projset4_instance1.lp > ../output_details/af_st_expanded_op392_projset4_instance1.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op4616_projset11_instance2.lp > ../output_details/af_st_expanded_op4616_projset11_instance2.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op4616_projset7_instance1.lp > ../output_details/af_st_expanded_op4616_projset7_instance1.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op528_projset3_instance1.lp > ../output_details/af_st_expanded_op528_projset3_instance1.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op576_projset3_instance2.lp > ../output_details/af_st_expanded_op576_projset3_instance2.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op7088_projset10_instance1.lp > ../output_details/af_st_expanded_op7088_projset10_instance1.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op7152_projset9_instance1.lp > ../output_details/af_st_expanded_op7152_projset9_instance1.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/af_st_expanded_op8_projset1.lp > ../output_details/af_st_expanded_op8_projset1.txt
echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/Hanoi.lp > ../output_details/Hanoi.txt
echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/Hanoi2.lp > ../output_details/Hanoi2.txt
#echo -e "3\nn" | python interp_proj_fasb.py ../input_instance/Hanoi3.lp > ../output_details/Hanoi3.txt
